services:
  postgres:
    image: postgres:lastest
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=porma_pro
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    environment:
      - DSN=postgresql://root:postgres@localhost:5432/porma_pro?ssl_mode=disable
      - ADDRESS=0.0.0.0:8080
    depends_on:
      - postgres
