// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package db

import (
	"context"
)

type Querier interface {
	CreateAccount(ctx context.Context, arg CreateAccountParams) (Account, error)
	CreatePersonalInfo(ctx context.Context, arg CreatePersonalInfoParams) (PersonalInfo, error)
	DeleteAccount(ctx context.Context, id int64) error
	DeletePersonalInfo(ctx context.Context, id int64) error
	GetAccount(ctx context.Context, id int64) (Account, error)
	GetAccountByEmail(ctx context.Context, email string) (Account, error)
	GetPersonalInfo(ctx context.Context, id int64) (PersonalInfo, error)
	UpdateAccount(ctx context.Context, arg UpdateAccountParams) (Account, error)
	UpdatePersonalInfo(ctx context.Context, arg UpdatePersonalInfoParams) (PersonalInfo, error)
	VerifyAccount(ctx context.Context, id int64) (Account, error)
}

var _ Querier = (*Queries)(nil)
