// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/kharljhon14/porma-pro-server/internal/db/sqlc (interfaces: Store)
//
// Generated by this command:
//
//	mockgen -destination internal/db/mock/store.go github.com/kharljhon14/porma-pro-server/internal/db/sqlc Store
//

// Package mock_db is a generated GoMock package.
package mock_db

import (
	context "context"
	reflect "reflect"

	sqlc "github.com/kharljhon14/porma-pro-server/internal/db/sqlc"
	gomock "github.com/golang/mock/gomock"
)

// MockStore is a mock of Store interface.
type MockStore struct {
	ctrl     *gomock.Controller
	recorder *MockStoreMockRecorder
	isgomock struct{}
}

// MockStoreMockRecorder is the mock recorder for MockStore.
type MockStoreMockRecorder struct {
	mock *MockStore
}

// NewMockStore creates a new mock instance.
func NewMockStore(ctrl *gomock.Controller) *MockStore {
	mock := &MockStore{ctrl: ctrl}
	mock.recorder = &MockStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStore) EXPECT() *MockStoreMockRecorder {
	return m.recorder
}

// CreateAccount mocks base method.
func (m *MockStore) CreateAccount(ctx context.Context, arg sqlc.CreateAccountParams) (sqlc.Account, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateAccount", ctx, arg)
	ret0, _ := ret[0].(sqlc.Account)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateAccount indicates an expected call of CreateAccount.
func (mr *MockStoreMockRecorder) CreateAccount(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateAccount", reflect.TypeOf((*MockStore)(nil).CreateAccount), ctx, arg)
}

// CreatePersonalInfo mocks base method.
func (m *MockStore) CreatePersonalInfo(ctx context.Context, arg sqlc.CreatePersonalInfoParams) (sqlc.PersonalInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreatePersonalInfo", ctx, arg)
	ret0, _ := ret[0].(sqlc.PersonalInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreatePersonalInfo indicates an expected call of CreatePersonalInfo.
func (mr *MockStoreMockRecorder) CreatePersonalInfo(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreatePersonalInfo", reflect.TypeOf((*MockStore)(nil).CreatePersonalInfo), ctx, arg)
}

// CreateSummary mocks base method.
func (m *MockStore) CreateSummary(ctx context.Context, arg sqlc.CreateSummaryParams) (sqlc.Summary, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateSummary", ctx, arg)
	ret0, _ := ret[0].(sqlc.Summary)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateSummary indicates an expected call of CreateSummary.
func (mr *MockStoreMockRecorder) CreateSummary(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateSummary", reflect.TypeOf((*MockStore)(nil).CreateSummary), ctx, arg)
}

// DeleteAccount mocks base method.
func (m *MockStore) DeleteAccount(ctx context.Context, id int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteAccount", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteAccount indicates an expected call of DeleteAccount.
func (mr *MockStoreMockRecorder) DeleteAccount(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteAccount", reflect.TypeOf((*MockStore)(nil).DeleteAccount), ctx, id)
}

// DeletePersonalInfo mocks base method.
func (m *MockStore) DeletePersonalInfo(ctx context.Context, id int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeletePersonalInfo", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeletePersonalInfo indicates an expected call of DeletePersonalInfo.
func (mr *MockStoreMockRecorder) DeletePersonalInfo(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeletePersonalInfo", reflect.TypeOf((*MockStore)(nil).DeletePersonalInfo), ctx, id)
}

// DeleteSummary mocks base method.
func (m *MockStore) DeleteSummary(ctx context.Context, id int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteSummary", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteSummary indicates an expected call of DeleteSummary.
func (mr *MockStoreMockRecorder) DeleteSummary(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteSummary", reflect.TypeOf((*MockStore)(nil).DeleteSummary), ctx, id)
}

// GetAccount mocks base method.
func (m *MockStore) GetAccount(ctx context.Context, id int64) (sqlc.Account, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAccount", ctx, id)
	ret0, _ := ret[0].(sqlc.Account)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAccount indicates an expected call of GetAccount.
func (mr *MockStoreMockRecorder) GetAccount(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAccount", reflect.TypeOf((*MockStore)(nil).GetAccount), ctx, id)
}

// GetAccountByEmail mocks base method.
func (m *MockStore) GetAccountByEmail(ctx context.Context, email string) (sqlc.Account, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAccountByEmail", ctx, email)
	ret0, _ := ret[0].(sqlc.Account)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAccountByEmail indicates an expected call of GetAccountByEmail.
func (mr *MockStoreMockRecorder) GetAccountByEmail(ctx, email any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAccountByEmail", reflect.TypeOf((*MockStore)(nil).GetAccountByEmail), ctx, email)
}

// GetPersonalInfo mocks base method.
func (m *MockStore) GetPersonalInfo(ctx context.Context, id int64) (sqlc.PersonalInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPersonalInfo", ctx, id)
	ret0, _ := ret[0].(sqlc.PersonalInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPersonalInfo indicates an expected call of GetPersonalInfo.
func (mr *MockStoreMockRecorder) GetPersonalInfo(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPersonalInfo", reflect.TypeOf((*MockStore)(nil).GetPersonalInfo), ctx, id)
}

// GetSummary mocks base method.
func (m *MockStore) GetSummary(ctx context.Context, id int64) (sqlc.Summary, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSummary", ctx, id)
	ret0, _ := ret[0].(sqlc.Summary)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSummary indicates an expected call of GetSummary.
func (mr *MockStoreMockRecorder) GetSummary(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSummary", reflect.TypeOf((*MockStore)(nil).GetSummary), ctx, id)
}

// UpdateAccount mocks base method.
func (m *MockStore) UpdateAccount(ctx context.Context, arg sqlc.UpdateAccountParams) (sqlc.Account, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateAccount", ctx, arg)
	ret0, _ := ret[0].(sqlc.Account)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateAccount indicates an expected call of UpdateAccount.
func (mr *MockStoreMockRecorder) UpdateAccount(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateAccount", reflect.TypeOf((*MockStore)(nil).UpdateAccount), ctx, arg)
}

// UpdatePersonalInfo mocks base method.
func (m *MockStore) UpdatePersonalInfo(ctx context.Context, arg sqlc.UpdatePersonalInfoParams) (sqlc.PersonalInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdatePersonalInfo", ctx, arg)
	ret0, _ := ret[0].(sqlc.PersonalInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdatePersonalInfo indicates an expected call of UpdatePersonalInfo.
func (mr *MockStoreMockRecorder) UpdatePersonalInfo(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdatePersonalInfo", reflect.TypeOf((*MockStore)(nil).UpdatePersonalInfo), ctx, arg)
}

// UpdateSummary mocks base method.
func (m *MockStore) UpdateSummary(ctx context.Context, arg sqlc.UpdateSummaryParams) (sqlc.Summary, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateSummary", ctx, arg)
	ret0, _ := ret[0].(sqlc.Summary)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateSummary indicates an expected call of UpdateSummary.
func (mr *MockStoreMockRecorder) UpdateSummary(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateSummary", reflect.TypeOf((*MockStore)(nil).UpdateSummary), ctx, arg)
}

// VerifyAccount mocks base method.
func (m *MockStore) VerifyAccount(ctx context.Context, id int64) (sqlc.Account, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "VerifyAccount", ctx, id)
	ret0, _ := ret[0].(sqlc.Account)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// VerifyAccount indicates an expected call of VerifyAccount.
func (mr *MockStoreMockRecorder) VerifyAccount(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VerifyAccount", reflect.TypeOf((*MockStore)(nil).VerifyAccount), ctx, id)
}
